In [1]:
#Importing the modules
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd 
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [24]:
#Loading the data sets
df = pd.read_csv('Datasets/covid_19_clean_data_Daywise(23-march).csv')
X = np.array(df[['Days']])
Y = np.array(df[['Confirmed','Deaths','Recovered']])
print(X[:4])
print(Y[:4])

[[1]
 [2]
 [3]
 [4]]
[[ 554   17   28]
 [ 652   18   30]
 [ 939   26   36]
 [1432   42   39]]


In [5]:
#Creating randon indices for spliting the data set
random_indices = np.random.permutation(61)


#Input train/test feature
X_train = X[random_indices[:58]]
X_test = X[random_indices[58:]]
print(X_train[:4])
print(X_test[:4])

#Output train/test feature
Y_train = Y[random_indices[:58]]
Y_test = Y[random_indices[58:]]
print(Y_train[:4])
print(Y_test[:4])

[[22]
 [55]
 [34]
 [25]]
[[58]
 [42]
 [45]]
[[ 45209   1118   5147]
 [181527   7126  78088]
 [ 79553   2629  25222]
 [ 69017   1666   9392]]
[[242708   9867  84854]
 [ 92767   3153  48221]
 [101567   3446  55858]]


In [6]:
#Normalizing the data
scaler = StandardScaler()
scaler.fit(X_train) # Computes the mean and standard deviation
X_train = scaler.transform(X_train) # Perform transformation: x = (x-mean)/std
X_test = scaler.transform(X_test)
print(X_train[:4])

[[-0.46234051]
 [ 1.42046744]
 [ 0.22231693]
 [-0.29117615]]


C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
#Creationg a keras mode
model = Sequential()
model.add(Dense(10, input_dim=X_train.shape[1],kernel_initializer='normal', activation='relu'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(3, activation='softmax')) # 'sigmoid'

model.add(Dense(3,kernel_initializer='normal'))
# Compile model
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy']) # 'binary_crossentropy'
    # 'adam', 'adagrad', 'sgd'

In [10]:
#Retriving the summery
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_4 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_5 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 33        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 12        
Total params: 285
Trainable params: 285
Non-trainable params: 0
_________________________________________________________________


In [11]:
#Finting the model
model.fit(X_train,Y_train,epochs=20)

Epoch 1/20
58/58 [==============================] - 1s 10ms/step - loss: 4631246539.0345 - acc: 1.0000
Epoch 2/20
58/58 [==============================] - 0s 188us/step - loss: 4631245841.6552 - acc: 1.0000
Epoch 3/20
58/58 [==============================] - 0s 234us/step - loss: 4631245594.4828 - acc: 1.0000
Epoch 4/20
58/58 [==============================] - 0s 233us/step - loss: 4631245206.0690 - acc: 1.0000
Epoch 5/20
58/58 [==============================] - 0s 218us/step - loss: 4631244694.0690 - acc: 1.0000
Epoch 6/20
58/58 [==============================] - 0s 252us/step - loss: 4631244376.2759 - acc: 1.0000
Epoch 7/20
58/58 [==============================] - 0s 249us/step - loss: 4631243855.4483 - acc: 1.0000
Epoch 8/20
58/58 [==============================] - 0s 219us/step - loss: 4631243970.2069 - acc: 1.0000
Epoch 9/20
58/58 [==============================] - 0s 169us/step - loss: 4631243564.1379 - acc: 1.0000
Epoch 10/20
58/58 [==============================] - 0s 207us/ste

In [12]:
print(model.predict(X_test))
print(Y_test)

[[0.0889803  0.0482337  0.07875752]
 [0.08894303 0.04839119 0.07870743]
 [0.08894877 0.0483616  0.07871874]]
[[242708   9867  84854]
 [ 92767   3153  48221]
 [101567   3446  55858]]


In [15]:
# evaluate the model
scores = model.evaluate(X_test, Y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

3/3 [==============================] - 0s 1ms/step

acc: 100.00%
